
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arlon-capi-nodelet-19-xenial-static
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: arlon-capi-nodelet-19
    namespace: default
  project: default
  source:
    repoURL: https://github.com/jayanth-tjvrr/arlon9
    path: clusters/arlon-capi-nodelet-19/workload/xenial-static
    targetRevision: HEAD
